name: "🐛 Bug Report"
description: We broke something, again
title: "[Bug]: "
labels: [needs triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the fields below.

  - type: textarea
    id: bug-steps
    attributes:
      label: What are the steps to reproduce this issue?
      placeholder: |
        1. Make new project
        2. Run `make package`
        3. ...
        4. See error
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: What happens?
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: bug-expectation
    attributes:
      label: What were you expecting to happen?
      description: A clear and concise description of what was supposed to happen.
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: bug-logs
    attributes:
      label: Any logs, error output, etc
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
        (If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
      render: shell

  - type: textarea
    id: bug-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.

  - type: markdown
    attributes:
      value: |
        Details from the host machine (what you use to build and package)

  - type: dropdown
    id: host-os
    attributes:
      label: What OS are you seeing the problem on?
      options:
        - iOS
        - macOS
        - Linux/WSL
        - Cygwin
    validations:
      required: true

  - type: input
    id: host-toolchain
    attributes:
      label: What toolchain and version are you using?
      placeholder: Xcode on macOS, LLCM+Clang elsewhere
    validations:
      required: true

  - type: input
    id: host-sdk
    attributes:
      label: Which SDK version are you using?
      placeholder: iOS 14.0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Details from the client device (what you use to test and run)

  - type: input
    id: client-model
    attributes:
      label: Which device model is it?
      placeholder: iPhone10,6
    validations:
      required: true

  - type: input
    id: client-os
    attributes:
      label: What OS version does it have installed?
      placeholder: iOS 14.0
    validations:
      required: true

  - type: input
    id: client-jailbreak
    attributes:
      label: Jailbreak
      placeholder: checkra1n
    validations:
      required: true
