name: Update-Submodules

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update submodules
        run: |
          git submodule update --remote --init --recursive
          git commit --all -m "[submodules] Update submodules to the latest commit"
          git push origin master
